### ISSUE TITLE
status is not being updated in Indigo

### ISSUE THREAD

**Issue by DrPitre** [FlyingDiver/Indigo-ratgdo#1]
Hey Joe,

Thanks for writing this plug-in! I have three ratgdo devices installed. All of them work with the plug-in. I can open and close them.

I exposed these in the HomeKitLink Siri plug-in as well and can open and close them in the Home app.

However, I'm noticing that the custom states in indigo aren't being updated for the light, availability, obstruction, and door. Are these still in the works?

**Comment by FlyingDiver** [comment]
That means you don't have the trigger properly configured, so updates from the ratgdo to the plugin (via MQTT) aren't received.
Probably.

**Comment by FlyingDiver** [comment]
Also, some of those are only sent out (by the ratgdo) at startup or if the status changes.

**Comment by DrPitre** [comment]
I had created the trigger.

I turned up debugging on the ratgdo plugin. Here's the log:

[ratgdo.log](https://github.com/FlyingDiver/Indigo-ratgdo/files/13775284/ratgdo.log)

The message that appears to be being sent is wrong:

```
2023-12-26 21:54:04.992	ratgdo GDO Controller Debug	message_handler: MQTT message ##systemstate## from \uc0\u9881 \u65039 MQTT Connector\
```

This is unexpected. I believe It should be `##ratgdo##` and not `##systemstate##`. I verified in the MQTT Connector that was automatically created that the message type is `##ratgdo##`

Also I looked in the plug-in, and light, obstruction, and availability aren't supported.

**Comment by FlyingDiver** [comment]
I'll need to see the trigger definition.  

What did you use to create that log file?  It looks like it was formatted in RTF, which messed it up.  Please use a plain text editor (like BBEdit) and repost.

**Comment by DrPitre** [comment]
I found the issue. I needed to go edit the MQTT Connector device and add "ratgdo/#" as a subscribed topic. Now things are working, including the updating of the light, availability, and obstruction. I didn't see that explicitly spelled out in the README. I may have missed it.

I can create an action to turn the light on or off by sending the appropriate MQTT command, so that will take care of that.

I believe you can close this issue.

**Comment by FlyingDiver** [comment]
I updated the README to include the required subscription.  Thanks for catching that.
